function onCreatePost()
	makeLuaText("power", "Power left:", 0, 25, screenHeight - 100)
	setTextSize("power", 22)
	setTextFont("power", "bite.ttf")
	setObjectCamera("power", 'hud')
	setTextBorder("power", 0, "0x")
	setProperty('power.alpha',0)
	addLuaText("power")

	makeLuaText("powerHP", "100", 0, getProperty("power.x") + getProperty("power.width") + 5,screenHeight - 100 - 22)
	setTextSize("powerHP", 36)
	setObjectCamera("powerHP", 'hud')
	setTextFont("powerHP", "bite.ttf")
	setTextBorder("powerHP", 0, "0x")
	setProperty('powerHP.alpha',0)
	addLuaText("powerHP")

	makeLuaText("powerpercent", "%", 0, getProperty("powerHP.x") + getProperty("powerHP.width"), screenHeight - 100)
	setTextSize("powerpercent", 22)
	setObjectCamera("powerpercent", 'hud')
	setTextFont("powerpercent", "bite.ttf")
	setTextBorder("powerpercent", 0, "0x")
	setProperty('powerpercent.alpha',0)
	addLuaText("powerpercent")
	setTextString("powerHP", getProperty("healthBar.percent"))
	setProperty('powerpercent.x',getProperty("powerHP.x") + getProperty("powerHP.width"))
end